user root;
worker_processes auto;
worker_rlimit_nofile 2048;

events {
    worker_connections 128;
    worker_aio_requests 32;
}

http {
    # Includes
    include mime.types;

    # Types
    types {
        application/csv csv;
        application/pdf terms;
    }

    # Buffering
    client_max_body_size 400m;
    client_body_buffer_size 10m;
    client_header_buffer_size 5k;
    client_header_timeout 10s;
    client_body_timeout 10s;
    send_timeout 10s;
    tcp_nopush on;
    sendfile on;
    sendfile_max_chunk 64m;
    keepalive_timeout 0;

    # Gzip
    gzip on;
    gzip_comp_level 3;
    gzip_types text/javascript text/css application/javascript font/woff font/ttf font/woff2;

    # Proxy
    proxy_set_header Host $host;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header Connection "";
    proxy_buffers 4 16m;

    upstream gunicorn {
        zone gunicorn 128K;
        server gunicorn:8000 max_fails=5;
        keepalive 15;
        keepalive_timeout 899;
        keepalive_time 3h;
    }

    # Servers
    server_tokens off;

    server {
        listen 80;
        server_name localhost;
        charset utf-8;
        proxy_http_version 1.1;

        location / {
            access_log /var/log/nginx/root.log;
            error_log /var/log/nginx/error.log;
            if ($request_method = 'OPTIONS') {
               add_header 'Access-Control-Allow-Origin' 'https://localhost';
               add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS, PUT, DELETE, PATCH';
               add_header 'Access-Control-Allow-Headers' 'DNT,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Range,Authorization';
               add_header 'Access-Control-Max-Age' 1728000;
               add_header 'Content-Type' 'text/plain; charset=utf-8';
               add_header 'Content-Length' 0;
               return 204;
            }
            add_header 'Access-Control-Allow-Origin' 'https://localhost' always;
            add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS, PUT, DELETE, PATCH' always;
            add_header 'Access-Control-Allow-Headers' 'DNT,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Range,Authorization' always;
            add_header 'Access-Control-Expose-Headers' 'Content-Length,Content-Range' always;
            proxy_pass http://gunicorn;
        }

        location /admin/ {
            access_log /var/log/nginx/admin.log;
            proxy_pass http://gunicorn;
        }

        location /static/ {
            access_log off;
            root /app;
            try_files $uri @not_found;
        }

        location /media/ {
            access_log off;
            root /app;
            try_files $uri @not_found;
        }

        location @not_found {
            return 404 "Requested resource was not found !";
        }
    }
}
