# Generated by Django 6.1 on 2026-08-11 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='attribute',
            new_name='shop_attrib_slug_f3652f_idx',
            old_name='shop_attrib_slug_idx',
        ),
        migrations.RenameIndex(
            model_name='attribute',
            new_name='shop_attrib_type_7cbea7_idx',
            old_name='shop_attrib_type_is_act_idx',
        ),
        migrations.RenameIndex(
            model_name='category',
            new_name='shop_catego_slug_5ac49f_idx',
            old_name='shop_catego_slug_idx',
        ),
        migrations.RenameIndex(
            model_name='category',
            new_name='shop_catego_parent__ddd4c7_idx',
            old_name='shop_catego_parent__idx',
        ),
        migrations.RenameIndex(
            model_name='category',
            new_name='shop_catego_is_acti_59c89f_idx',
            old_name='shop_catego_is_acti_idx',
        ),
        migrations.RenameIndex(
            model_name='product',
            new_name='shop_produc_slug_76971b_idx',
            old_name='shop_produc_slug_idx',
        ),
        migrations.RenameIndex(
            model_name='product',
            new_name='shop_produc_categor_c9aecd_idx',
            old_name='shop_produc_categor_idx',
        ),
        migrations.RenameIndex(
            model_name='product',
            new_name='shop_produc_is_acti_8b5353_idx',
            old_name='shop_produc_is_acti_idx',
        ),
        migrations.RenameIndex(
            model_name='productimage',
            new_name='shop_produc_product_9fb734_idx',
            old_name='shop_produ_product_img_idx',
        ),
        migrations.RenameIndex(
            model_name='productimage',
            new_name='shop_produc_variant_109c14_idx',
            old_name='shop_produ_variant_idx',
        ),
        migrations.RenameIndex(
            model_name='productvariant',
            new_name='shop_produc_sku_e6b8d5_idx',
            old_name='shop_produ_sku_idx',
        ),
        migrations.RenameIndex(
            model_name='productvariant',
            new_name='shop_produc_product_27d2af_idx',
            old_name='shop_produ_product_idx',
        ),
    ]
