# Generated by Django 6.1 on 2026-08-11 14:58

import common.images.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_rename_shop_attrib_slug_idx_shop_attrib_slug_f3652f_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=common.images.fields.ProcessedImageField(method=6, quality=85, upload_to='products/gallery/', variants={'card': {'mode': 'cover', 'size': (600, 600)}, 'detail': {'mode': 'cover', 'size': (1200, 1200)}, 'thumb': {'mode': 'cover', 'size': (300, 300)}}),
        ),
    ]
